// ─── Region Master Data ───────────────────────────────────────────────────────
// เพิ่มประเทศใหม่ที่นี่ที่เดียว แล้วทุกที่จะใช้ได้เลย


// AFTER
export const COUNTRY_DISPLAY: Record<string, { name: string; flag: string }> = {
  // ── เอเชียตะวันออกเฉียงใต้ ──────────────────────────────────────────────
  TH: { name: "Thailand",             flag: "th" },
  SG: { name: "Singapore",            flag: "sg" },
  MY: { name: "Malaysia",             flag: "my" },
  ID: { name: "Indonesia",            flag: "id" },
  PH: { name: "Philippines",          flag: "ph" },
  VN: { name: "Vietnam",              flag: "vn" },
  MM: { name: "Myanmar",              flag: "mm" },
  LA: { name: "Laos",                 flag: "la" },
  KH: { name: "Cambodia",             flag: "kh" },
  BN: { name: "Brunei",               flag: "bn" },
  TL: { name: "Timor-Leste",          flag: "tl" },

  // ── เอเชียตะวันออก ───────────────────────────────────────────────────────
  CN: { name: "China",                flag: "cn" },
  JP: { name: "Japan",                flag: "jp" },
  KR: { name: "South Korea",          flag: "kr" },
  TW: { name: "Taiwan",               flag: "tw" },
  HK: { name: "Hong Kong",            flag: "hk" },
  MO: { name: "Macau",                flag: "mo" },
  MN: { name: "Mongolia",             flag: "mn" },

  // ── เอเชียใต้ ────────────────────────────────────────────────────────────
  IN: { name: "India",                flag: "in" },
  PK: { name: "Pakistan",             flag: "pk" },
  BD: { name: "Bangladesh",           flag: "bd" },
  LK: { name: "Sri Lanka",            flag: "lk" },
  NP: { name: "Nepal",                flag: "np" },

  // ── เอเชียตะวันตก / ตะวันออกกลาง ────────────────────────────────────────
  AE: { name: "UAE",                  flag: "ae" },
  SA: { name: "Saudi Arabia",         flag: "sa" },
  QA: { name: "Qatar",                flag: "qa" },
  KW: { name: "Kuwait",               flag: "kw" },
  BH: { name: "Bahrain",              flag: "bh" },
  OM: { name: "Oman",                 flag: "om" },
  IL: { name: "Israel",               flag: "il" },
  TR: { name: "Turkey",               flag: "tr" },
  JO: { name: "Jordan",               flag: "jo" },
  LB: { name: "Lebanon",              flag: "lb" },

  // ── ยุโรป ────────────────────────────────────────────────────────────────
  GB: { name: "United Kingdom",       flag: "gb" },
  FR: { name: "France",               flag: "fr" },
  DE: { name: "Germany",              flag: "de" },
  IT: { name: "Italy",                flag: "it" },
  ES: { name: "Spain",                flag: "es" },
  NL: { name: "Netherlands",          flag: "nl" },
  CH: { name: "Switzerland",          flag: "ch" },
  SE: { name: "Sweden",               flag: "se" },
  NO: { name: "Norway",               flag: "no" },
  DK: { name: "Denmark",              flag: "dk" },
  FI: { name: "Finland",              flag: "fi" },
  PT: { name: "Portugal",             flag: "pt" },
  GR: { name: "Greece",               flag: "gr" },
  AT: { name: "Austria",              flag: "at" },
  BE: { name: "Belgium",              flag: "be" },
  PL: { name: "Poland",               flag: "pl" },
  CZ: { name: "Czech Republic",       flag: "cz" },
  HU: { name: "Hungary",              flag: "hu" },
  RO: { name: "Romania",              flag: "ro" },
  RU: { name: "Russia",               flag: "ru" },

  // ── โอเชียเนีย ───────────────────────────────────────────────────────────
  AU: { name: "Australia",            flag: "au" },
  NZ: { name: "New Zealand",          flag: "nz" },

  // ── อเมริกา ──────────────────────────────────────────────────────────────
  US: { name: "United States",        flag: "us" },
  CA: { name: "Canada",               flag: "ca" },
  MX: { name: "Mexico",               flag: "mx" },
  BR: { name: "Brazil",               flag: "br" },

  // ── แอฟริกา ──────────────────────────────────────────────────────────────
  ZA: { name: "South Africa",         flag: "za" },
  EG: { name: "Egypt",                flag: "eg" },
  NG: { name: "Nigeria",              flag: "ng" },
  KE: { name: "Kenya",                flag: "ke" },
};
export const OTHER_CITY = "other";
export const OTHER_CITY_LABEL = "อื่นๆ";
// TH เท่านั้น — whitelist 77 จังหวัด + ชื่อภาษาอังกฤษ
export const TH_CITIES: string[] = [ 
        "กรุงเทพมหานคร",
        "กระบี่",
        "กาญจนบุรี",
        "กาฬสินธุ์",
        "กำแพงเพชร",
        "ขอนแก่น",
        "จันทบุรี",
        "ฉะเชิงเทรา",
        "ชลบุรี",
        "ชัยนาท",
        "ชัยภูมิ",
        "ชุมพร",
        "เชียงราย",
        "เชียงใหม่",
        "ตรัง",
        "ตราด",
        "ตาก",
        "นครนายก",
        "นครปฐม",
        "นครพนม",
        "นครราชสีมา",
        "นครศรีธรรมราช",
        "นครสวรรค์",
        "นนทบุรี",
        "นราธิวาส",
        "น่าน",
        "บึงกาฬ",
        "บุรีรัมย์",
        "ปทุมธานี",
        "ประจวบคีรีขันธ์",
        "ปราจีนบุรี",
        "ปัตตานี",
        "พระนครศรีอยุธยา",
        "พะเยา",
        "พังงา",
        "พัทลุง",
        "พิจิตร",
        "พิษณุโลก",
        "เพชรบุรี",
        "เพชรบูรณ์",
        "แพร่",
        "ภูเก็ต",
        "มหาสารคาม",
        "มุกดาหาร",
        "แม่ฮ่องสอน",
        "ยโสธร",
        "ยะลา",
        "ร้อยเอ็ด",
        "ระนอง",
        "ระยอง",
        "ราชบุรี",
        "ลพบุรี",
        "ลำปาง",
        "ลำพูน",
        "เลย",
        "ศรีสะเกษ",
        "สกลนคร",
        "สงขลา",
        "สตูล",
        "สมุทรปราการ",
        "สมุทรสงคราม",
        "สมุทรสาคร",
        "สระแก้ว",
        "สระบุรี",
        "สิงห์บุรี",
        "สุโขทัย",
        "สุพรรณบุรี",
        "สุราษฎร์ธานี",
        "สุรินทร์",
        "หนองคาย",
        "หนองบัวลำภู",
        "อ่างทอง",
        "อำนาจเจริญ",
        "อุดรธานี",
        "อุตรดิตถ์",
        "อุทัยธานี",
        "อุบลราชธานี",
        "Bangkok",
        "Krabi",
        "Kanchanaburi",
        "Kalasin",
        "Kamphaeng Phet",
        "Khon Kaen",
        "Chanthaburi",
        "Chachoengsao",
        "Chonburi",
        "Chai Nat",
        "Chaiyaphum",
        "Chumphon",
        "Chiang Rai",
        "Chiang Mai",
        "Trang",
        "Trat",
        "Tak",
        "Nakhon Nayok",
        "Nakhon Pathom",
        "Nakhon Phanom",
        "Nakhon Ratchasima",
        "Nakhon Si Thammarat",
        "Nakhon Sawan",
        "Nonthaburi",
        "Narathiwat",
        "Nan",
        "Bueng Kan",
        "Buriram",
        "Pathum Thani",
        "Prachuap Khiri Khan",
        "Prachin Buri",
        "Pattani",
        "Phra Nakhon Si Ayutthaya",
        "Phayao",
        "Phang Nga",
        "Phatthalung",
        "Phichit",
        "Phitsanulok",
        "Phetchaburi",
        "Phetchabun",
        "Phrae",
        "Phuket",
        "Maha Sarakham",
        "Mukdahan",
        "Mae Hong Son",
        "Yasothon",
        "Yala",
        "Roi Et",
        "Ranong",
        "Rayong",
        "Ratchaburi",
        "Lopburi",
        "Lampang",
        "Lamphun",
        "Loei",
        "Sisaket",
        "Sakon Nakhon",
        "Songkhla",
        "Satun",
        "Samut Prakan",
        "Samut Songkhram",
        "Samut Sakhon",
        "Sa Kaeo",
        "Saraburi",
        "Sing Buri",
        "Sukhothai",
        "Suphan Buri",
        "Surat Thani",
        "Surin",
        "Nong Khai",
        "Nong Bua Lamphu",
        "Ang Thong",
        "Amnat Charoen",
        "Udon Thani",
        "Uttaradit",
        "Uthai Thani",
        "Ubon Ratchathani",
        "Pattaya",
        "Pattaya City",
        "Muang Pattaya",
        "Nongprue",
        "Khlong Nueng",
        "Ao Salat",
        "Ban Suan",
        "Jomtien",
        "Na Jomtien",
        "Pattaya Beach",
        "Pattaya City Center",
        "Pattaya Central",
        "Pattaya South",
        "Pattaya North",
        "Pattaya East",


];

// รวม cities ทุกประเทศ
export function getCitiesByCountry(country: string): string[] {
  return country === "TH" ? TH_CITIES : [];
}

export function isOtherCity(city: string): boolean {
  return city === OTHER_CITY;
}