// ─── Region Master Data ───────────────────────────────────────────────────────
// เพิ่มประเทศใหม่ที่นี่ที่เดียว แล้วทุกที่จะใช้ได้เลย

export type CountryCode = "TH" | "HK" | "LA" | "MM" | "TR";

export const COUNTRY_LABELS: Record<string, { name: string; flag: string }> = {
    TH: { name: "Thailand", flag: "th" },
    HK: { name: "Hong Kong", flag: "hk" },
    LA: { name: "Laos", flag: "la" },
    MM: { name: "Myanmar", flag: "mm" },
    TR: { name: "Turkey", flag: "tr" },
};
export const OTHER_CITY = "other";
export const OTHER_CITY_LABEL = "อื่นๆ";
export const REGIONS: Record<string, string[]> = {
    TH: [
        "กรุงเทพมหานคร",
        "กระบี่",
        "กาญจนบุรี",
        "กาฬสินธุ์",
        "กำแพงเพชร",
        "ขอนแก่น",
        "จันทบุรี",
        "ฉะเชิงเทรา",
        "ชลบุรี",
        "ชัยนาท",
        "ชัยภูมิ",
        "ชุมพร",
        "เชียงราย",
        "เชียงใหม่",
        "ตรัง",
        "ตราด",
        "ตาก",
        "นครนายก",
        "นครปฐม",
        "นครพนม",
        "นครราชสีมา",
        "นครศรีธรรมราช",
        "นครสวรรค์",
        "นนทบุรี",
        "นราธิวาส",
        "น่าน",
        "บึงกาฬ",
        "บุรีรัมย์",
        "ปทุมธานี",
        "ประจวบคีรีขันธ์",
        "ปราจีนบุรี",
        "ปัตตานี",
        "พระนครศรีอยุธยา",
        "พะเยา",
        "พังงา",
        "พัทลุง",
        "พิจิตร",
        "พิษณุโลก",
        "เพชรบุรี",
        "เพชรบูรณ์",
        "แพร่",
        "ภูเก็ต",
        "มหาสารคาม",
        "มุกดาหาร",
        "แม่ฮ่องสอน",
        "ยโสธร",
        "ยะลา",
        "ร้อยเอ็ด",
        "ระนอง",
        "ระยอง",
        "ราชบุรี",
        "ลพบุรี",
        "ลำปาง",
        "ลำพูน",
        "เลย",
        "ศรีสะเกษ",
        "สกลนคร",
        "สงขลา",
        "สตูล",
        "สมุทรปราการ",
        "สมุทรสงคราม",
        "สมุทรสาคร",
        "สระแก้ว",
        "สระบุรี",
        "สิงห์บุรี",
        "สุโขทัย",
        "สุพรรณบุรี",
        "สุราษฎร์ธานี",
        "สุรินทร์",
        "หนองคาย",
        "หนองบัวลำภู",
        "อ่างทอง",
        "อำนาจเจริญ",
        "อุดรธานี",
        "อุตรดิตถ์",
        "อุทัยธานี",
        "อุบลราชธานี",
        "Bangkok",
        "Krabi",
        "Kanchanaburi",
        "Kalasin",
        "Kamphaeng Phet",
        "Khon Kaen",
        "Chanthaburi",
        "Chachoengsao",
        "Chonburi",
        "Chai Nat",
        "Chaiyaphum",
        "Chumphon",
        "Chiang Rai",
        "Chiang Mai",
        "Trang",
        "Trat",
        "Tak",
        "Nakhon Nayok",
        "Nakhon Pathom",
        "Nakhon Phanom",
        "Nakhon Ratchasima",
        "Nakhon Si Thammarat",
        "Nakhon Sawan",
        "Nonthaburi",
        "Narathiwat",
        "Nan",
        "Bueng Kan",
        "Buriram",
        "Pathum Thani",
        "Prachuap Khiri Khan",
        "Prachin Buri",
        "Pattani",
        "Phra Nakhon Si Ayutthaya",
        "Phayao",
        "Phang Nga",
        "Phatthalung",
        "Phichit",
        "Phitsanulok",
        "Phetchaburi",
        "Phetchabun",
        "Phrae",
        "Phuket",
        "Maha Sarakham",
        "Mukdahan",
        "Mae Hong Son",
        "Yasothon",
        "Yala",
        "Roi Et",
        "Ranong",
        "Rayong",
        "Ratchaburi",
        "Lopburi",
        "Lampang",
        "Lamphun",
        "Loei",
        "Sisaket",
        "Sakon Nakhon",
        "Songkhla",
        "Satun",
        "Samut Prakan",
        "Samut Songkhram",
        "Samut Sakhon",
        "Sa Kaeo",
        "Saraburi",
        "Sing Buri",
        "Sukhothai",
        "Suphan Buri",
        "Surat Thani",
        "Surin",
        "Nong Khai",
        "Nong Bua Lamphu",
        "Ang Thong",
        "Amnat Charoen",
        "Udon Thani",
        "Uttaradit",
        "Uthai Thani",
        "Ubon Ratchathani",
        "Pattaya",
        "Pattaya City",
        "Muang Pattaya",
        "Nongprue",
        "Khlong Nueng",
        "Ao Salat",
        "Ban Suan",
    ],

    HK: [
        "Central and Western",
        "Eastern",
        "Southern",
        "Wan Chai",
        "Kowloon City",
        "Kwun Tong",
        "Sham Shui Po",
        "Wong Tai Sin",
        "Yau Tsim Mong",
        "Islands",
        "Kwai Tsing",
        "North",
        "Sai Kung",
        "Sha Tin",
        "Tai Po",
        "Tsuen Wan",
        "Tuen Mun",
        "Yuen Long",
        "Hong Kong Island",
        "Kowloon",
        "New Territories",
        "Central",
        "Admiralty",
        "Sheung Wan",
        "Causeway Bay",
        "Tsim Sha Tsui",
        "Mong Kok",
        "Yau Ma Tei",
        "Jordan",
        // ← เพิ่มตรงนี้
        "Prince Edward",
        "Aberdeen",
        "Lantau Island",
        "Kennedy Town",
        "North Point",
        "Quarry Bay",
        "Taikoo",
        "Sai Wan Ho",
        "Hung Hom",
        "To Kwa Wan",
        "Kowloon Tong",
        "Diamond Hill",
        "Ngau Tau Kok",
        "Lam Tin",
        "Tseung Kwan O",
        "Clearwater Bay",
        "Fanling",
        "Sheung Shui",
        "Tai Wai",
        "Ma On Shan",
        "Tung Chung",
        "Mui Wo",
        "Cheung Chau",
        "Lamma Island",
    ],

    LA: [
        "Vientiane",
        "Vientiane Prefecture",
        "Phongsali",
        "Luang Namtha",
        "Oudomxay",
        "Bokeo",
        "Luang Prabang",
        "Huaphanh",
        "Xayabury",
        "Xieng Khouang",
        "Vientiane Province",
        "Bolikhamsai",
        "Khammouane",
        "Savannakhet",
        "Saravane",
        "Sekong",
        "Champasak",
        "Attapeu",
    ],

    MM: [
        "Yangon",
        "Mandalay",
        "Naypyidaw",
        "Sagaing",
        "Magway",
        "Bago",
        "Ayeyarwady",
        "Tanintharyi",
        "Mon",
        "Kayin",
        "Kayah",
        "Chin",
        "Kachin",
        "Shan",
        "Rakhine",
    ],

    TR: [
        "Istanbul",
        "Ankara",
        "Izmir",
        "Bursa",
        "Antalya",
        "Adana",
        "Konya",
        "Gaziantep",
        "Mersin",
        "Diyarbakir",
    ],
};

// รวม cities ทุกประเทศ
export const ALL_CITIES = Object.values(REGIONS).flat();

// ดึง cities ของประเทศเดียว
export function getCitiesByCountry(country: string): string[] {
    return REGIONS[country] ?? [];
}

// ดึง cities หลายประเทศ
export function getCitiesByCountries(countries: string[]): string[] {
    return countries.flatMap((c) => REGIONS[c] ?? []);
}

export function isOtherCity(city: string): boolean {
    return city === OTHER_CITY;
}